In [1]:
import pandas as pd

In [3]:
pd.read_csv("users1.csv")

   firstName lastName
0      Mohit   Golchi
1     golchi      NaN
2      Mohit    Singh
3      mosdf      sad
4      mosdf      sad
5      mosdf      sad
6      mosdf      sad
7      mosdf      sad
8      mosdf      sad
9      mosdf      sad
10     Admin    Admin
11   Prakash    Singh
12  Priyansh      Raj
13   Vaibhav      Roy